server:
  port: 8080
logging:
  level: debug
  file: log.log
  max-age: 7
  max-size: 1024
process:
  cache:
    expiration: 1800
    cleanup-interval: 900
  directory:
    test: data/process/test/
    release: data/process/release/
tokenizer:
  extra-dict: data/dict/dict.txt.small
  stop-words: data/dict/stop_words.txt
session:
  cache:
    expiration: 1800
    cleanup-interval: 900
