server:
  port: 8080
logging:
  level: debug
  file: log.log
  max-age: 7
  max-size: 1024
process:
  directory:
    test: /opt/deployments/process/test/
    release: /opt/deployments/process/release/
tokenizer:
  dict-file: data/dict/dict.txt.small
